### ISSUE TITLE
How to change the background color?

### ISSUE THREAD

**Issue by slovebj** [ryu1kn/vscode-partial-diff#20]
How to change the background color?
The background color difference between the different text and the surrounding text is not obvious, how can it be modified into a more different background color？
Thank you！

**Comment by ryu1kn** [comment]
Hi @slovebj , for these kind of issues, providing screenshots would be really helpful 😉 

Anyway, isn't that also true for any other diffs that are not generated by Partial Diff, like git diff view or compare 2 files view? as Partial Diff does nothing about the colouring.

If the problem exists with other diff views, I think it's because of the theme.

https://code.visualstudio.com/docs/getstarted/theme-color-reference#_diff-editor-colors

**Comment by ryu1kn** [comment]
Did my comment answer your question? I'm closing this.
